<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.2.0</Version>
    <Authors>TekLot</Authors>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
