<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailForge\MailForge.csproj" />
    <ProjectReference Include="..\MailForge.Smtp\MailForge.Smtp.csproj" />
    <ProjectReference Include="..\MailForge.Resend\MailForge.Resend.csproj" />
    <ProjectReference Include="..\MailForge.AmazonSES\MailForge.AmazonSES.csproj" />
    <ProjectReference Include="..\MailForge.Postmark\MailForge.Postmark.csproj" />
    <ProjectReference Include="..\MailForge.Brevo\MailForge.Brevo.csproj" />
    <ProjectReference Include="..\MailForge.ZeptoMail\MailForge.ZeptoMail.csproj" />
    <ProjectReference Include="..\MailForge.Mailgun\MailForge.Mailgun.csproj" />
  </ItemGroup>

</Project>
