<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Copyright>Copyright © 2026 TekLot</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailForge\MailForge.csproj" />
    <ProjectReference Include="..\MailForge.Smtp\MailForge.Smtp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="FluentHtml.Core" Version="0.5.0" />
    <PackageReference Include="FluentHtml.Http" Version="0.5.0" />
    <PackageReference Include="FluentHtml.Htmx" Version="0.5.0" />
    <PackageReference Include="FluentHtml.Bootstrap" Version="0.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>